[project]
name = "sotf"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "pandas>=2.2",
  "numpy>=2.0",
  "yfinance>=0.2.50",
  "matplotlib>=3.8",
  "scipy>=1.12",
  "pyyaml>=6.0.1",
]

[tool.setuptools.packages.find]
where = ["src"]
